openapi: 3.0.0
info:
  title: Modello Dati Schede - Dati comuni
  version: 1.0.0
components:
  schemas:
    TipologicaType:
      description: oggetto che contiene i valori delle tipologiche
      type: object
      properties:
        codice:
          description: codice della tipologica
          type: string
        descrizione:
          description: descrizione della voce della tipologica
          type: string
